name: Actions on Satvik's work
on:
  push:
    branches:
      - main
  pull_request:
    types:
      - closed
    branches:
      - main
jobs:
  test-docker-image:
    runs-on: ubuntu-latest
    container: satvik97/satvik-mishra
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Run tests in Python_scripts directory
        run: |
          python Python_scripts/testing_script.py
