name: Actions on Satvik's work
on: [push]
jobs:
  test-docker-image:
    runs-on: ubuntu-latest
    container: satvik97/satvik-mishra
    steps:
     - name: Check out repository
       uses: actions/checkout@v3
     - name: Login to dockerhub
       uses: docker/login-action@v1
       with:
          username: satvik97
          password: ${{ secrets.DOCKERHUB_TOKEN }}
       
     - name: Check that we have vim installed
       run: test -f /bin/vim && echo "Vim is installed"
     - name: Run tests in tests/satvik directory
       run: |
          cd tests/satvik
          pytest
