name: Actions on Satvik's work
on:
  push:
    branches:
      - main
  pull_request:
    types:
      - closed
    branches:
      - main
jobs:
  test-docker-image:
    runs-on: ubuntu-latest
    container: satvik97/satvik-mishra
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
      - name: Check that we have vim installed
        run: test -f /bin/vim && echo "Vim is installed"
      - name: Run tests in tests/satvik directory
        run: |
          cd tests/satvik
          pytest

  docker-availability:
    runs-on: ubuntu-latest
    steps:
      - name: Check docker availability
        run: docker --version
      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u satvik97 --password-stdin
      - name: Run the Test Job
        run: |
          docker run --rm -v $PWD:/repo -w /repo satvik97/satvik-mishra /bin/bash -c "cd tests/satvik && pytest"

