name: Actions on Satvik's work
on: [push]
jobs:
  test-docker-image:
    runs-on: ubuntu-latest
    container: satvik97/satvik-mishra
    steps:
     - name: Check out repository
       uses: actions/checkout@v3
     - name: Login to dockerhub
       env:
          DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
       run: echo "${DOCKERHUB_TOKEN}" | docker login -u satvik97 --password-stdin
     - name: Check that we have vim installed
       run: test -f /bin/vim && echo "Vim is installed"
     - name: Run tests in tests/satvik directory
       run: |
          cd tests/satvik
          pytest
